### ISSUE TITLE
RStudio Server 1.4.1717

### ISSUE THREAD

**Issue by stillill** [mcw-rcc/bc_rcc_rstudio_server#1]
What you have works great for RStudio Server 1.3.959 however I had issues when using it with RStudio Server 1.4.1717. It seems I could never get connected to the RStudio Server session. Any chance you could add support for RStudio Server 1.4.1717? Unfortunately, it appears in order to use R 4.1.0 in RStudio Server one needs to use 1.4.1717 due to the R graphics engine  version 14 in R 4.1.0 not being supported by any older versions of RStudio.

**Comment by maflister** [comment]
That's correct. RStudio Server 1.4.XXX requires some updates. While we were not able to get this to work, some folks did post success stories on the OOD discourse page. I believe it starts around https://discourse.osc.edu/t/rstudio-when-launched-without-singularity-is-having-strange-troubles-with-authentication/1213/32?u=maflister.

Also, I was not aware that R 4.1.0 had a dependency on 1.4.1717. We're still using R 4.0.4 and RStudio Server 1.3. Hopefully the discourse discussion helps!

**Comment by maflister** [comment]
We did finally get 1.4 working. Please check new branch "rstudio-1.4-updates". You could also download files from tag v1.3.0. Let us know if that works for you.

**Comment by stillill** [comment]
Thanks so much for doing these updates! I tried out the updated app using RStudio Server 1.4.1717. I slightly modified the form.yml,  submit.yml, and manifest.yml files for our site. In template/script.sh.erb I changed some of the boilerplate code at the top to correspond to our modules, but kept everything below the `# Start RStudio Server` line. At any rate, when I click on "Connect to RStudio Server" button I get an error message "Error: Temporary server error, please try again." Do you have any idea why this might be happening? I tried entering in the password from the session connection.yml file and my user id but that then throws a "requested page not found" error.

<img width="267" alt="server_error" src="https://user-images.githubusercontent.com/13002626/128426402-0ef20dfb-61ad-4aac-9cf5-c271bb8b0b40.png">

<img width="388" alt="notfound" src="https://user-images.githubusercontent.com/13002626/128426426-7026a7fa-59dc-42af-97ee-f2a8cd096033.png">

**Comment by maflister** [comment]
Do you see an entry for a csrf_token in your connection.yml file?

**Comment by stillill** [comment]
Hey, I don't see a crsf_token field in the connection.yml file. All I see are entries for host, port, and password. It looks like the contents of connection.yml are set according to the view.html.erb file? I definitely didn't change the view.html.erb file. I see the tag in view.html.erb specifying "crsf-token" but unfortunately that doesn't appear in the generated connection.yml file.

**Comment by maflister** [comment]
The csrf_token is defined in before.sh.erb. Then the conn_params setting in submit.yml.erb adds it to the connection.yml and makes it available to use in view.html.erb. If you don't see it in connection.yml, then please run another job and check if you see a csrf_token in the before.sh file.

**Comment by stillill** [comment]
Thanks so much for the explanation. There was a crsf_token in the session before.sh file. Using what you wrote, I was able to figure out what I did wrong. When I modified the submit.yml.erb file I had removed the conn_params setting without thinking; adding it back in fixed the error and the updated app now works for me. I appreciated your help with this!
