### ISSUE TITLE
problems setting this up

### ISSUE THREAD

**Issue by dtenenba** [mcw-rcc/bc_rcc_rstudio_server#2]
Hi,

First of all, please let me know if this is the appropriate place for a problem report. If you prefer I can delete this issue and instead make a post on the Open OnDemand forum.

I am having some problems getting this interactive app to work. I should mention a couple things right off:

* I am using Ubuntu 20.04. Our institution is an Ubuntu shop so this is a pretty hard requirement.
* I am not using any modules at the moment, I have installed R and RStudio Server via the OS package manager (apt-get) (right now I am just trying to get a demo working; later we will be using modules).

The problem:

When I start up an instance of this interactive app and click "Connect To Rstudio Server", I get a login screen. Entering my usual PAM password does not work. Looking at the code it appears that a random password is set. I temporarily commented that out and set RSTUDIO_PASSWORD to a known password so I could at least log in. But then I got a page that said:

```
RStudio Server

The requested page was not found.

Please contact your system administrator for assistance, or click [here](https://oodnode.my.org/rnode/slurmnode1/11325/appUri#) to go back.
```

The URL in the address bar at this point is:  `https://oodnode.my.org/rnode/slurmnode1/11325/appUri`
(I changed the org name but otherwise that's it).

If I change `--auth-none` from 0 to 1, then I do not get a login screen, but I do get a popup dialog that says:

```
Cannot Connect to R Session

Could not connect to the R session on RStudio Server.

Unable to connect to Service (1)
```

With a `Retry` button. Clicking it produces the same dialog again. At this point my URL is 

`https://oodnode.my.org/rnode/slurmnode1/6928/`

When I run `ps` on the compute node where RStudio Server is running, I see the `rserver` process. I do not see an `rsession` process, not sure if I am supposed to.

There are no logs in /var/log/rstudio-server or /var/log/rstudio. 

Any tips on how to troubleshoot this?

Thanks.

**Comment by maflister** [comment]
Hi Dan,

I'll try to help fix this and if we fail, we can take it over to the OOD discourse. 

We don't use Ubuntu so my first question is whether you have any other OOD apps already running correctly? That would rule out some non-app issues. Second question is what version of RStudio and R do you have installed? 

Please set `--auth-none=0` again, run the app as before, and report back the contents of your `output.log`.

Thanks,
-Matt

**Comment by dtenenba** [comment]
Hi Matt, thanks for looking at this and for the quick reply.

I have other OOD apps running - on the batch connect side, an [example shiny app](https://github.com/CHPC-UofU/bc_osc_example_shiny), [Jupyter](https://github.com/OSC/bc_example_jupyter), an [example python flask app](https://github.com/dtenenba/bc_example_flaskapp) I wrote myself, and on the Passenger side, another python flask [wsgi/passenger example](https://github.com/dtenenba/flask_passenger_wsgi_hello).

I set `--auth-none` back to 0 and ran the app (logging in with the password that I hacked in instead of the random one) and this is the output. I don't see any obvious problems. It does try to call the `module` command a bunch of times and fails, because I did not bother to comment out those calls to `module` - I don't have lmod installed. This is all in a slurm cluster that is a set of [docker containers](https://github.com/dtenenba/slurm-cluster) which is why it does not have some basic things installed.

```
/var/spool/slurmd/job00003/slurm_script: line 3: module: command not found
Script starting...
Waiting for RStudio Server to open port 26277...
/home/admin/ondemand/data/sys/dashboard/batch_connect/dev/bc_rcc_rstudio_server/output/b415fa07-2d74-4db1-996d-e0065f5d39be/script.sh: line 7: module: command not found
/home/admin/ondemand/data/sys/dashboard/batch_connect/dev/bc_rcc_rstudio_server/output/b415fa07-2d74-4db1-996d-e0065f5d39be/script.sh: line 10: module: command not found
/home/admin/ondemand/data/sys/dashboard/batch_connect/dev/bc_rcc_rstudio_server/output/b415fa07-2d74-4db1-996d-e0065f5d39be/script.sh: line 13: module: command not found
/home/admin/ondemand/data/sys/dashboard/batch_connect/dev/bc_rcc_rstudio_server/output/b415fa07-2d74-4db1-996d-e0065f5d39be/script.sh: line 48: module: command not found
Starting up rserver...
+ /usr/lib/rstudio-server/bin/rserver --database-config-file /home/admin/ondemand/dev/bc_rcc_rstudio_server/database.conf --www-port 26277 --auth-none 0 --auth-pam-helper-path /home/admin/ondemand/data/sys/dashboard/batch_connect/dev/bc_rcc_rstudio_server/output/b415fa07-2d74-4db1-996d-e0065f5d39be/bin/auth --auth-encrypt-password 0 --rsession-path /home/admin/ondemand/data/sys/dashboard/batch_connect/dev/bc_rcc_rstudio_server/output/b415fa07-2d74-4db1-996d-e0065f5d39be/rsession.sh --server-data-dir /tmp --secure-cookie-key-file /tmp/rstudio-server/secure-cookie-key --server-user admin
Discovered RStudio Server listening on port 26277!
Generating connection YAML file...

```

You can see that I tweaked the `rserver` command a little bit, I had to add `--server-user` and `--database-config-file` to  avoid errors. 

I am running R-4.2.0 and the version of the apt rstudio-server package is 2022.02.2+485.

**Comment by maflister** [comment]
That helps. I think you may need to start from the rstudio-1.4-updates branch (https://github.com/mcw-rcc/bc_rcc_rstudio_server/tree/rstudio-1.4-updates). RStudio Server 1.4 introduced some breaking changes for the OOD app including the database.conf and a CSRF token requirement. I suspect that you're seeing the CSRF token issue. Suggest to change to the "newer" branch and apply your customizations there.

For reference, CSRF token fixes are in `submit.yml.erb`, `view.html.erb`, and `template/before.sh.erb`. 

I need to clean up this repo since most folks aren't using older versions of RStudio Server and its not entirely obvious that you should use the other branch. Apologies if that caused confusion. 

Hope that helps!

**Comment by dtenenba** [comment]
It works! I had to re-add `--server-user $USER` to the `rserver` command, and make other tweaks custom to my installation. But it worked! And out of the box my library paths look correct and I am able to do plots (two most common issues with our current rinkydink rstudio server setup). And I did not have to authenticate to rstudio server. 

Not super important at all, but I am getting this warning:

```
Warning message:
Character set is not UTF-8; please change your locale 
```

That might have to do with the settings on the compute node. 

Thanks very much for your help, much appreciated. We will definitely use this in production (with modules) going forward. Having the ability to run RStudio Server without Singularity is a big win for us, so thanks for making this.

Please let me know if you merge the 1.4 branch into master. Until then I'll continue to use the 1.4 branch in my fork.

**Comment by maflister** [comment]
Glad to hear it. We'll add that flag and clean up some other things to generalize. I'll merge it tonight or tomorrow. I don't think anyone is installing older versions anymore.

I would guess the character set is inherited from the OS setting. Not sure if there is an Renviron or Rprofile.site setting for that.

**Comment by rpique** [comment]
I maybe having the same issue. 
"When I start up an instance of this interactive app and click "Connect To Rstudio Server", I get a login screen." "

Not sure if the changes were merged with the main. I used the main branch.

**Comment by maflister** [comment]
We did merge changes into the master branch. What version of R and RStudio Server are you using?

**Comment by rpique** [comment]
I used the following. 

R: R version 4.1.0 (2021-05-18) -- "Camp Pontanezen"

Rstudio, I tried:
1) 2022.07.2+576 (Spotted Wakerobin) for CentOS 7
2) 2022.02.2+485 (Prairie Trillium) for CentOS 7
but I got similar results with both. 

This is the output.log output:
```
Script starting...
Waiting for RStudio Server to open port 22550...

Currently Loaded Modules:
  1) gnu7/7.3.0   2) R/4.1.0

Starting up rserver...
++ whoami
+ rserver --www-port 22550 --auth-none 0 --auth-pam-helper-path /wsu/home/fe/fe01/fe0105/ondemand/data/sys/dashboard/batch_connect/dev/Rstudio5/output/46e7dce1-3f67-4462-8e71-7a8f78597dbe/bin/auth --auth-encrypt-password 0 --rsession-path /wsu/home/fe/fe01/fe0105/ondemand/data/sys/dashboard/batch_connect/dev/Rstudio5/output/46e7dce1-3f67-4462-8e71-7a8f78597dbe/rsession.sh --server-data-dir /tmp --secure-cookie-key-file /tmp/rstudio-server/secure-cookie-key --database-config-file /wsu/home/fe/fe01/fe0105/ondemand/data/sys/dashboard/batch_connect/dev/Rstudio5/output/46e7dce1-3f67-4462-8e71-7a8f78597dbe/database.conf --server-user fe0105
Discovered RStudio Server listening on port 22550!
Generating connection YAML file...
```
<img width="366" alt="image" src="https://user-images.githubusercontent.com/762404/195428526-7912a164-ab6e-4823-8f67-0ec70d2211b5.png">

**Comment by maflister** [comment]
We've tested those combinations so that is not an issue. Please post your `before.sh.erb`, `submit.yml.erb`, and `view.html.erb` scripts. Also, what do you use for TMPDIR in your cluster?

**Comment by rpique** [comment]
TMPDIR, is set up by slurm. 

before.sh.erb
```
# Export the module function if it exists
[[ $(type -t module) == "function" ]] && export -f module

# Find available port to run server on
port=$(find_port)

# Define a password and export it for RStudio authentication
##password="potato"
password="$(create_passwd 16)"
export RSTUDIO_PASSWORD="${password}"

# Define CSRF_TOKEN and export it for auth
<%-
  require 'securerandom'
  csrftoken=SecureRandom.uuid
-%>
export csrf_token="<%= csrftoken %>"
```

submit.yml.erb
```
<%-
cores_number = cores.blank? ? 1 : cores.to_i
memory_amount = memory.blank? ? 1 : memory.to_i
%>

---
batch_connect:
  template: "basic"
  conn_params:
    - csrftoken
script:
  email: <%= ENV["USER"] %>@wayne.edu
  wall_time: <%= (bc_num_hours.blank? ? 24 : bc_num_hours.to_i) * 3600 %>
  native:
    - "-J"
    - "OnDemand: Rstudio Piquelab"
    - "-q"
    - "<%= qos %>"
    - "-N"
    - "1-1"
    - "-n"
    - "<%= cores_number %>"
    - "--mem=<%= memory_amount %>G"
    - "-t"
    - "<%= (bc_num_hours.blank? ? 24 : bc_num_hours.to_i) * 60 %>"
```

view.html.erb
```
<script>
  document.cookie = "csrf-token=<%= csrf_token %>; path=/rnode/<%= host %>/<%= port %>; secure";
</script>
<form action="/rnode/<%= host %>/<%= port %>/auth-do-sign-in" method="post" target="_blank">
  <input type="hidden" name="username" value="<%= ENV["USER"] %>">
  <input type="hidden" name="password" value="<%= password %>">
  <input type="hidden" name="staySignedIn" value="1">
  <input type="hidden" name="appUri" value="">
  <input type="hidden" name="csrf-token" value="<%= csrf_token %>"/>
  <button class="btn btn-primary" type="submit">
    <i class="fa fa-registered"></i> Connect to 5RStudio Server
  </button>
</form>
```

**Comment by maflister** [comment]
Ok. That all looks fine. Might be an issue with your TMPDIR if it is not unique to your user. You could confirm this by checking the syslog on the compute node. Another quick test is explicitly set TMPDIR in `script.sh.erb` to something unique, i.e., `export TMPDIR="$(mktemp -d)"` or a path in your home directory.

**Comment by rpique** [comment]
I logged in to the compute node: 
```
[fe0105@rpr12 slurm.5309762.0]$ pwd -P
/tmp/slurm.5309762.0
[fe0105@rpr12 slurm.5309762.0]$ tree
.
├── tmp
│   ├── fe0105
│   │   └── 5309762
│   │       └── rstudio-server
│   │           └── db
│   │               └── rstudio-os.sqlite
│   ├── hello.txt
│   ├── rstudio-rserver
│   │   └── session-server-rpc.socket
│   ├── rstudio-rsession
│   └── rstudio-server
│       ├── secure-cookie-key
│       └── session-rpc-key
└── var_tmp

9 directories, 5 files
```
It seems that TMPDIR is working, but I also tried the `export TMPDIR="$(mktemp -d)"` and I got the same result.

**Comment by maflister** [comment]
In your `submit.yml.erb` change `csrftoken` to `csrf_token`.

**Comment by rpique** [comment]
That was it! Thank you so much!!!
I feel bad for missing that typo! I must have inherited it from earlier trials. 

The plotting is working as well now. They should make this the main example in the OSC. 

If found your repo thorough: https://discourse.openondemand.org/t/rstudio-without-singularity/773/12 
and it has been what has helped me the most.

**Comment by maflister** [comment]
Thanks for letting me know. Glad our example is helping.
